$src = ".\src"
New-Item -ItemType Directory -Force -Path "$src\pages"
New-Item -ItemType Directory -Force -Path "$src\features\auth"
New-Item -ItemType Directory -Force -Path "$src\features\dashboard"
New-Item -ItemType Directory -Force -Path "$src\features\employees"
New-Item -ItemType Directory -Force -Path "$src\features\attendance"
New-Item -ItemType Directory -Force -Path "$src\components\layout"
New-Item -ItemType Directory -Force -Path "$src\contexts"
Move-Item -Path "$src\components\dashboard\Overview.tsx" -Destination "$src\pages\OverviewPage.tsx"
Move-Item -Path "$src\components\dashboard\Overview.test.tsx" -Destination "$src\pages\OverviewPage.test.tsx"
Move-Item -Path "$src\components\dashboard\Settings.tsx" -Destination "$src\pages\SettingsPage.tsx"
Move-Item -Path "$src\components\dashboard\EmployeeList.tsx" -Destination "$src\pages\EmployeesPage.tsx"
Move-Item -Path "$src\components\dashboard\EmployeeList.test.tsx" -Destination "$src\pages\EmployeesPage.test.tsx"
Move-Item -Path "$src\components\dashboard\AttendanceLogs.tsx" -Destination "$src\pages\AttendancePage.tsx"
Move-Item -Path "$src\components\dashboard\AttendanceLogs.test.tsx" -Destination "$src\pages\AttendancePage.test.tsx"
Move-Item -Path "$src\components\auth\Login.tsx" -Destination "$src\pages\LoginPage.tsx"
Move-Item -Path "$src\components\auth\Login.test.tsx" -Destination "$src\pages\LoginPage.test.tsx"
Move-Item -Path "$src\components\auth\ProtectedRoute.tsx" -Destination "$src\features\auth\ProtectedRoute.tsx"
Move-Item -Path "$src\components\auth\ProtectedRoute.test.tsx" -Destination "$src\features\auth\ProtectedRoute.test.tsx"
Move-Item -Path "$src\components\dashboard\HourlyAreaChart.tsx" -Destination "$src\features\dashboard\HourlyAreaChart.tsx"
Move-Item -Path "$src\components\dashboard\DoorStatusGrid.tsx" -Destination "$src\features\dashboard\DoorStatusGrid.tsx"
Move-Item -Path "$src\components\dashboard\ChartSkeleton.tsx" -Destination "$src\features\dashboard\ChartSkeleton.tsx"
Move-Item -Path "$src\components\dashboard\PunctualityDonutChart.tsx" -Destination "$src\features\dashboard\PunctualityDonutChart.tsx"
Move-Item -Path "$src\components\dashboard\WeeklyBarChart.tsx" -Destination "$src\features\dashboard\WeeklyBarChart.tsx"
Move-Item -Path "$src\components\dashboard\AddEmployeeModal.tsx" -Destination "$src\features\employees\AddEmployeeModal.tsx"
Move-Item -Path "$src\components\dashboard\AddEmployeeModal.test.tsx" -Destination "$src\features\employees\AddEmployeeModal.test.tsx"
Move-Item -Path "$src\components\dashboard\EmployeeDetailModal.tsx" -Destination "$src\features\employees\EmployeeDetailModal.tsx"
Move-Item -Path "$src\components\dashboard\EmployeeDetailModal.test.tsx" -Destination "$src\features\employees\EmployeeDetailModal.test.tsx"
Move-Item -Path "$src\components\dashboard\DashboardShell.tsx" -Destination "$src\components\layout\DashboardShell.tsx"
Move-Item -Path "$src\components\dashboard\DashboardShell.test.tsx" -Destination "$src\components\layout\DashboardShell.test.tsx"
Move-Item -Path "$src\components\App.test.tsx" -Destination "$src\App.test.tsx"
Move-Item -Path "$src\lib\app-context.tsx" -Destination "$src\contexts\app-context.tsx"
Move-Item -Path "$src\lib\app-data-context.tsx" -Destination "$src\contexts\app-data-context.tsx"
Move-Item -Path "$src\lib\app-data-context.test.tsx" -Destination "$src\contexts\app-data-context.test.tsx"
Remove-Item -Path "$src\components\dashboard" -Force -Recurse
Remove-Item -Path "$src\components\auth" -Force -Recurse
