import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type Theme = "dark" | "light";
type Lang = "vi" | "en";

const dict = {
  vi: {
    "nav.overview": "Tổng quan",
    "nav.attendance": "Chấm công",
    "nav.employees": "Nhân viên",
    "nav.settings": "Cài đặt",
    "nav.management": "Quản lý",
    "nav.logout": "Đăng xuất",
    "system.online": "Hệ thống online",
    "system.sync": "Sync: 2s · 8/8 cửa hoạt động",
    "search.placeholder": "Tìm nhân viên, UID thẻ...",
    
    // OverviewPage
    "overview.greeting.morning": "Chào buổi sáng",
    "overview.greeting.afternoon": "Chào buổi chiều",
    "overview.greeting.evening": "Chào buổi tối",
    "overview.refresh": "Làm mới",
    "overview.stats.registered": "Đã đăng ký",
    "overview.stats.todayCheckins": "Check-in hôm nay",
    "overview.stats.noCheckins": "Chưa có ai check-in hôm nay",
    "overview.stats.ontimeCount": "{count} đúng giờ",
    "overview.stats.todayLate": "Đi trễ hôm nay",
    "overview.stats.goodJob": "✓ Tốt lắm!",
    "overview.stats.needsAttention": "Cần chú ý",
    "overview.stats.ontimeRate": "Tỷ lệ đúng giờ",
    "overview.stats.noData": "Chưa có dữ liệu",
    "overview.stats.outOf": "Trên {count} lượt",
    "overview.chart.hourlyVolume": "Lưu lượng check-in hôm nay",
    "overview.chart.hourlyPeak": "Cao điểm: {time}",
    "overview.chart.hourlyVolumeUnit": "lượt",
    "overview.chart.hourlyPeakPrefix": "Cao điểm",
    "overview.chart.attendanceRatio": "Tỷ lệ chấm công",
    "overview.chart.attendanceRatioSub": "Hôm nay · {count} lượt",
    "overview.chart.peopleUnit": "người",
    "overview.chart.trend7Days": "Xu hướng 7 ngày",
    "overview.chart.weeklyTotal": "Tổng tuần: {count} lượt",
    "overview.chart.weeklyTotalSub": "7 ngày gần nhất",
    "overview.chart.doorStatus": "Trạng thái cửa",
    "overview.chart.doorStatusSub": "Realtime · cập nhật mỗi 2s",
    "overview.chart.doorActive": "Hoạt động",
    "overview.chart.doorClosed": "Đóng",
    "overview.chart.doorError": "Lỗi",
    "overview.recentCheckins": "Check-in gần đây",
    "overview.recent.subReal": "Hôm nay · {count} lượt tổng",
    "overview.recent.subDemo": "demo · hiển thị khi có dữ liệu thực",
    "overview.table.employee": "Nhân viên",
    "overview.table.department": "Phòng ban",
    "overview.table.checkinTime": "Giờ check-in",
    "overview.table.status": "Trạng thái",
    "overview.table.noCheckinsToday": "Chưa có check-in nào hôm nay",
    
    // AttendancePage
    "attendance.title": "Chấm công",
    "attendance.subtitle": "Lịch sử quẹt thẻ NFC theo ngày",
    "attendance.date": "Ngày",
    "attendance.uid": "UID",
    "attendance.name": "Nhân viên",
    "attendance.dept": "Phòng ban",
    "attendance.checkin": "Vào",
    "attendance.checkout": "Ra",
    "attendance.status": "Trạng thái",
    "attendance.ontime": "Đúng giờ",
    "attendance.late": "Trễ",
    "attendance.absent": "Vắng",
    "attendance.filter.all": "Tất cả trạng thái",
    "attendance.search.placeholder": "Tìm theo tên hoặc UID...",
    "attendance.export": "Xuất Excel",
    "attendance.stats.lateCount": "{count} trễ",
    "attendance.stats.absentCount": "{count} vắng",
    "attendance.table.title": "Nhật ký chấm công",
    "attendance.table.records": "{count} bản ghi",
    "attendance.table.shift": "Ca vào",
    "attendance.table.noData": "Không tìm thấy dữ liệu",
    
    // EmployeesPage
    "employees.title": "Nhân viên",
    "employees.subtitle": "Danh sách nhân viên công ty",
    "employees.add": "Thêm nhân viên",
    "employees.id": "Mã NV",
    "employees.uid": "UID thẻ NFC",
    "employees.name": "Họ tên",
    "employees.dept": "Phòng ban",
    "employees.shift": "Giờ vào ca",
    "employees.email": "Email",
    "employees.status": "Trạng thái",
    "employees.active": "Đang làm việc",
    "employees.inactive": "Tạm nghỉ",
    "employees.search": "Tìm theo tên, UID, phòng ban...",
    "employees.actions": "Thao tác",
    "employees.delete": "Xoá",
    "employees.cancel": "Huỷ",
    "employees.save": "Lưu nhân viên",
    "employees.new": "Nhân viên mới",
    "employees.total": "Tổng nhân viên",
    "employees.table.title": "Danh sách nhân viên",
    "employees.table.count": "{count} nhân viên",
    "employees.search.placeholder": "Tìm kiếm theo tên hoặc mã NV",
    "employees.filter.allDepts": "Tất cả phòng ban",
    "employees.details": "Chi tiết",
    "employees.table.noData": "Không tìm thấy nhân viên phù hợp",
    
    // SettingsPage
    "settings.title": "Cài đặt",
    "settings.subtitle": "Tuỳ chỉnh giao diện và ngôn ngữ hệ thống",
    "settings.appearance": "Giao diện",
    "settings.theme": "Chế độ hiển thị",
    "settings.theme.dark": "Tối",
    "settings.theme.light": "Sáng",
    "settings.language": "Ngôn ngữ",
    "settings.language.vi": "Tiếng Việt",
    "settings.language.en": "English",
    "settings.profile": "Hồ sơ quản trị",
    "settings.profile.name": "Họ tên",
    "settings.profile.email": "Email",
    "settings.profile.role": "Vai trò",
    "settings.notifications": "Thông báo",
    "settings.notif.late": "Cảnh báo nhân viên đi trễ",
    "settings.notif.offline": "Cảnh báo thiết bị offline",
    "settings.notif.daily": "Báo cáo cuối ngày qua email",
    "settings.shift": "Ca làm việc",
    "settings.shift.start": "Giờ bắt đầu ca",
    "settings.shift.late": "Ngưỡng đi trễ (phút)",
    "settings.data": "Dữ liệu",
    "settings.data.export": "Xuất dữ liệu chấm công (CSV)",
    "settings.data.sync": "Đồng bộ Google Sheets ngay",
    "settings.saved": "Đã lưu",
    "settings.sidebar.title": "Cài đặt hệ thống",
    "settings.nav.connection": "Kết nối hệ thống",
    "settings.nav.doors": "Cấu hình cửa",
    "settings.nav.admin": "Tài khoản Admin",
    "settings.nav.about": "Về hệ thống",
    "settings.connection.subtitle": "Cấu hình kết nối giữa phần cứng ESP32 và server.",
    "settings.connection.serverUrl": "URL Server (Google Apps Script)",
    "settings.connection.apiKey": "API Key Xác Thực",
    "settings.connection.timeout": "Timeout (ms)",
    "settings.saveChanges": "Lưu thay đổi",
    "settings.seed.title": "Khởi tạo dữ liệu mẫu",
    "settings.seed.subtitle": "Tạo dữ liệu chấm công lịch sử mẫu trên Google Sheets.",
    "settings.seed.description": "Nếu bạn chưa có dữ liệu quẹt thẻ thực tế hoặc muốn hiển thị các biểu đồ trên trang tổng quan đầy đủ nhất, nhấp vào nút dưới đây để tạo tự động dữ liệu chấm công mẫu cho hôm nay và 7 ngày trước đó trên Google Sheets.",
    "settings.seed.loading": "Đang khởi tạo...",
    "settings.doors.subtitle": "Thiết lập tham số vật lý cho Servo và khóa điện từ.",
    "settings.doors.servoOpen": "Góc Servo Mở (độ)",
    "settings.doors.servoClose": "Góc Servo Đóng (độ)",
    "settings.doors.autoCloseTime": "Thời gian mở tự động đóng lại (giây)",
    "settings.notifications.title": "Cấu hình thông báo",
    "settings.notifications.subtitle": "Tuỳ chỉnh thông báo cảnh báo và email báo cáo.",
    "settings.notif.late.desc": "Gửi thông báo telegram hoặc email khi nhân viên đi muộn quá 15 phút.",
    "settings.notif.offline.desc": "Gửi cảnh báo tức thời khi thiết bị ESP32 mất kết nối internet quá 5 phút.",
    "settings.notif.daily.desc": "Tự động tổng hợp và gửi báo cáo chấm công của toàn công ty lúc 18:00 hàng ngày.",
    "settings.admin.title": "Tài khoản quản trị",
    "settings.admin.subtitle": "Quản lý tài khoản đăng nhập hệ thống console.",
    "settings.admin.fullname": "Họ tên quản trị viên",
    "settings.admin.email": "Email / Username",
    "settings.admin.changePassword": "Đổi mật khẩu đăng nhập",
    "settings.admin.currentPassword": "Mật khẩu hiện tại",
    "settings.admin.newPassword": "Mật khẩu mới",
    "settings.admin.confirmPassword": "Xác nhận mật khẩu mới",
    "settings.admin.updateAccount": "Cập nhật tài khoản",
    "settings.about.statusOk": "Hệ thống hoạt động bình thường",
    "settings.about.iotSpecs": "Thông số thiết bị IoT",
    "settings.about.mcuName": "Tên vi điều khiển:",
    "settings.about.nfcSensor": "Cảm biến NFC:",
    "settings.about.lockMotor": "Động cơ khóa:",
    "settings.about.networkConnection": "Kết nối mạng:",
    "settings.about.devInfo": "Thông tin phát triển",
    "settings.about.devDescription": "Hệ thống được phát triển tích hợp hoàn chỉnh giữa phần cứng IoT (ESP32 quẹt thẻ NFC/RFID) và phần mềm điều khiển lưu trữ trực tiếp trên đám mây Google Sheets API thông qua Google Apps Script Web App.",
    "settings.about.viewDocs": "Xem tài liệu hướng dẫn lắp đặt (ADR.md)",
    
    // Global / Common
    "system.loading": "Đang tải...",
    "system.error.connection": "Đang mất kết nối...",
  },
  en: {
    "nav.overview": "Overview",
    "nav.attendance": "Attendance",
    "nav.employees": "Employees",
    "nav.settings": "Settings",
    "nav.management": "Management",
    "nav.logout": "Logout",
    "system.online": "System online",
    "system.sync": "Sync: 2s · 8/8 doors active",
    "search.placeholder": "Search employee, card UID...",
    
    // OverviewPage
    "overview.greeting.morning": "Good morning",
    "overview.greeting.afternoon": "Good afternoon",
    "overview.greeting.evening": "Good evening",
    "overview.refresh": "Refresh",
    "overview.stats.registered": "Registered",
    "overview.stats.todayCheckins": "Today's check-ins",
    "overview.stats.noCheckins": "No check-ins today",
    "overview.stats.ontimeCount": "{count} on time",
    "overview.stats.todayLate": "Late today",
    "overview.stats.goodJob": "✓ Good job!",
    "overview.stats.needsAttention": "Needs attention",
    "overview.stats.ontimeRate": "Punctuality rate",
    "overview.stats.noData": "No data",
    "overview.stats.outOf": "Out of {count} check-ins",
    "overview.chart.hourlyVolume": "Today's check-in volume",
    "overview.chart.hourlyPeak": "Peak: {time}",
    "overview.chart.hourlyVolumeUnit": "check-ins",
    "overview.chart.hourlyPeakPrefix": "Peak",
    "overview.chart.attendanceRatio": "Attendance status ratio",
    "overview.chart.attendanceRatioSub": "Today · {count} check-ins",
    "overview.chart.peopleUnit": "people",
    "overview.chart.trend7Days": "7-day trend",
    "overview.chart.weeklyTotal": "Weekly total: {count} check-ins",
    "overview.chart.weeklyTotalSub": "Last 7 days",
    "overview.chart.doorStatus": "Door status",
    "overview.chart.doorStatusSub": "Realtime · updated every 2s",
    "overview.chart.doorActive": "Active",
    "overview.chart.doorClosed": "Closed",
    "overview.chart.doorError": "Error",
    "overview.recentCheckins": "Recent check-ins",
    "overview.recent.subReal": "Today · {count} total check-ins",
    "overview.recent.subDemo": "demo · shown when real data is available",
    "overview.table.employee": "Employee",
    "overview.table.department": "Department",
    "overview.table.checkinTime": "Check-in time",
    "overview.table.status": "Status",
    "overview.table.noCheckinsToday": "No check-ins today",
    
    // AttendancePage
    "attendance.title": "Attendance",
    "attendance.subtitle": "NFC scan history by date",
    "attendance.date": "Date",
    "attendance.uid": "UID",
    "attendance.name": "Employee",
    "attendance.dept": "Department",
    "attendance.checkin": "Check-in",
    "attendance.checkout": "Check-out",
    "attendance.status": "Status",
    "attendance.ontime": "On time",
    "attendance.late": "Late",
    "attendance.absent": "Absent",
    "attendance.filter.all": "All statuses",
    "attendance.search.placeholder": "Search by name or UID...",
    "attendance.export": "Export Excel",
    "attendance.stats.lateCount": "{count} late",
    "attendance.stats.absentCount": "{count} absent",
    "attendance.table.title": "Attendance log",
    "attendance.table.records": "{count} records",
    "attendance.table.shift": "Shift start",
    "attendance.table.noData": "No data found",
    
    // EmployeesPage
    "employees.title": "Employees",
    "employees.subtitle": "Company employee directory",
    "employees.add": "Add employee",
    "employees.id": "Employee ID",
    "employees.uid": "NFC Card UID",
    "employees.name": "Full name",
    "employees.dept": "Department",
    "employees.shift": "Shift start",
    "employees.email": "Email",
    "employees.status": "Status",
    "employees.active": "Active",
    "employees.inactive": "Inactive",
    "employees.search": "Search by name, UID, department...",
    "employees.actions": "Actions",
    "employees.delete": "Delete",
    "employees.cancel": "Cancel",
    "employees.save": "Save employee",
    "employees.new": "New employee",
    "employees.total": "Total employees",
    "employees.table.title": "Employee list",
    "employees.table.count": "{count} employees",
    "employees.search.placeholder": "Search by name or Employee ID...",
    "employees.filter.allDepts": "All departments",
    "employees.details": "Details",
    "employees.table.noData": "No matching employees found",
    
    // SettingsPage
    "settings.title": "Settings",
    "settings.subtitle": "Customize interface and language",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.theme.dark": "Dark",
    "settings.theme.light": "Light",
    "settings.language": "Language",
    "settings.language.vi": "Vietnamese",
    "settings.language.en": "English",
    "settings.profile": "Admin profile",
    "settings.profile.name": "Full name",
    "settings.profile.email": "Email",
    "settings.profile.role": "Role",
    "settings.notifications": "Notifications",
    "settings.notif.late": "Alert on late arrivals",
    "settings.notif.offline": "Alert on offline devices",
    "settings.notif.daily": "Daily report via email",
    "settings.shift": "Work shift",
    "settings.shift.start": "Shift start time",
    "settings.shift.late": "Late threshold (minutes)",
    "settings.data": "Data",
    "settings.data.export": "Export attendance (CSV)",
    "settings.data.sync": "Sync Google Sheets now",
    "settings.saved": "Saved",
    "settings.sidebar.title": "System settings",
    "settings.nav.connection": "System connection",
    "settings.nav.doors": "Door configuration",
    "settings.nav.admin": "Admin account",
    "settings.nav.about": "About system",
    "settings.connection.subtitle": "Configure connection between ESP32 hardware and server.",
    "settings.connection.serverUrl": "Server URL (Google Apps Script)",
    "settings.connection.apiKey": "Authentication API Key",
    "settings.connection.timeout": "Timeout (ms)",
    "settings.saveChanges": "Save changes",
    "settings.seed.title": "Initialize mock data",
    "settings.seed.subtitle": "Create historic mock attendance data on Google Sheets.",
    "settings.seed.description": "If you do not have actual card swipe data or want to display the full charts on the overview page, click the button below to automatically generate mock attendance data for today and the previous 7 days on Google Sheets.",
    "settings.seed.loading": "Initializing...",
    "settings.doors.subtitle": "Set physical parameters for Servo and electromagnetic lock.",
    "settings.doors.servoOpen": "Servo Open Angle (degrees)",
    "settings.doors.servoClose": "Servo Close Angle (degrees)",
    "settings.doors.autoCloseTime": "Auto-close duration (seconds)",
    "settings.notifications.title": "Notification configuration",
    "settings.notifications.subtitle": "Customize alert notifications and report emails.",
    "settings.notif.late.desc": "Send telegram or email notification when employee is late by more than 15 minutes.",
    "settings.notif.offline.desc": "Send instant alert when ESP32 device loses internet connection for more than 5 minutes.",
    "settings.notif.daily.desc": "Automatically aggregate and send the entire company's attendance report daily at 18:00.",
    "settings.admin.title": "Admin account",
    "settings.admin.subtitle": "Manage console login account.",
    "settings.admin.fullname": "Admin full name",
    "settings.admin.email": "Email / Username",
    "settings.admin.changePassword": "Change login password",
    "settings.admin.currentPassword": "Current password",
    "settings.admin.newPassword": "New password",
    "settings.admin.confirmPassword": "Confirm new password",
    "settings.admin.updateAccount": "Update account",
    "settings.about.statusOk": "System operating normally",
    "settings.about.iotSpecs": "IoT Device Specifications",
    "settings.about.mcuName": "Microcontroller:",
    "settings.about.nfcSensor": "NFC Sensor:",
    "settings.about.lockMotor": "Lock Motor:",
    "settings.about.networkConnection": "Network connection:",
    "settings.about.devInfo": "Development Info",
    "settings.about.devDescription": "The system is developed as a complete integration between IoT hardware (ESP32 NFC/RFID swipe) and control software stored directly on the Google Sheets API cloud via Google Apps Script Web App.",
    "settings.about.viewDocs": "View installation guide documentation (ADR.md)",
    
    // Global / Common
    "system.loading": "Loading...",
    "system.error.connection": "Connecting/Error...",
  },
} as const;

type Key = keyof (typeof dict)["vi"];

interface AppCtx {
  theme: Theme;
  setTheme: (t: Theme) => void;
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: Key) => string;
}

const Ctx = createContext<AppCtx | null>(null);

export function AppProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(() => {
    return (localStorage.getItem("theme") as Theme | null) ?? "light";
  });
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("lang") as Lang | null) ?? "vi";
  });

  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove("dark", "light");
    root.classList.add(theme);
    localStorage.setItem("theme", theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem("lang", lang);
  }, [lang]);

  const t = (k: Key) => dict[lang][k] ?? k;

  return (
    <Ctx.Provider value={{ theme, setTheme: setThemeState, lang, setLang: setLangState, t }}>
      {children}
    </Ctx.Provider>
  );
}

export function useApp() {
  const c = useContext(Ctx);
  if (!c) throw new Error("useApp must be used within AppProvider");
  return c;
}
